name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4


      - name: Update CloudFormation stack
        shell: bash
        run: |
          STACK_NAME="s3-prod-stack"
          REGION="eu-north-1"

          aws cloudformation create-change-set \
            --stack-name $STACK_NAME \
            --change-set-name create-s3-bucket \
            --change-set-type CREATE \
            --template-body file://templates/s3.yaml \
            --parameters file://params/dev.json


