name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4


      - name: Update CloudFormation stack
        shell: bash
        run: |
          STACK_NAME="s3-dev-stack"
          REGION="eu-north-1"

          aws cloudformation create-stack \
            --stack-name $STACK_NAME \
            --template-body file://templates/s3.yaml \
            --region $REGION \
            --parameters ParameterKey=Env,ParameterValue=dev


          aws cloudformation describe-stacks \
            --stack-name $STACK_NAME \
            --query "Stacks[0].Outputs"
